stages:
  - fetch
  - build

fetch:
  stage: fetch
  image:
    name: genshen/pkg:0.4.1-clang10-mpi
    entrypoint: [""]
  tags:
    - cpp
    - pkg
  cache:
    key: pkg_cache_misamd_namespace
    paths:
      - pkg_cache
  variables:
    PKG_AUTH: 'gitlab-ci-token?${CI_JOB_TOKEN}@git.hpcer.dev'
  before_script:
    - mkdir -p pkg_cache
    - ln -s $(pwd)/pkg_cache ~/.pkg
  script:
    - pkg fetch
    - pkg install --verbose
    - rm -rf vendor/cache vendor/src
  artifacts:
    paths:
      - vendor
      - pkg.dep.cmake

build:
  stage: build
  image:
    name: genshen/pkg:0.4.1-clang10-mpi
    entrypoint: [""]
  tags:
    - cpp
    - pkg
  script:
    - cmake -Bcmake-build -DCMAKE_BUILD_TYPE=Debug -H.
    - make -Ccmake-build
  artifacts:
    paths: # all binary are static linked, so just pass binary
      - cmake-build/bin
  dependencies:
    - fetch
